version: '3'
services:
  tests:
    build:
      # Context specifies where all of the files should come from
      context: .
      dockerfile: Dockerfile.coverage
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "coverage"]